name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: install dependencies
        run: "python -m pip install pylint"
      - name: lint
        run: "make lint"
      - name: tests
        run: "make test"
